version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8000:80
    restart: unless-stopped

  proxy:
    build: ./proxy
    ports:
      - 5000:80
    depends_on:
      - backend-1
      - backend-2
    restart: unless-stopped

  backend-1:
    build: ./backend
    environment:
      POSTGRES_CONNECTION_URL: postgres://postgres:password@postgres:5432/postgres
    ports:
      - 5001:5000
      - 6001:6000
    depends_on:
      - postgres
    restart: unless-stopped

  backend-2:
    build: ./backend
    environment:
      POSTGRES_CONNECTION_URL: postgres://postgres:password@postgres:5432/postgres
    ports:
      - 5002:5000
      - 6002:6000
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped

  bot:
    build: ./bot
    restart: unless-stopped

  grafana:
    image: grafana/grafana:6.1.6
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.9.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
