version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8000:80
    restart: unless-stopped

  proxy:
    build: ./proxy
    ports:
      - 5000:80
    depends_on:
      - backend-1
    restart: unless-stopped

  backend-1:
    build: ./backend
    ports:
      - 5001:5000
    restart: unless-stopped
