apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgresql:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: "password"
    jsonData:
      sslmode: "disable"
    editable: true
