{
 "title": "Flask",
 "description": "Visualise the behaviour of the Flask REST APIs.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "delta",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "api", "query": "app_flask_http_request_total" }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flask Total HTTP Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_flask_http_request_total[$delta]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total by Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flask Total HTTP Calls by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total by Status Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flask Total HTTP Calls by Status Code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total by Status Code and API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flask Total HTTP Calls by Status Code and API - $api",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "repeat": "api",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total{endpoint=\"$api\"}[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Flask Total HTTP Calls by Status Code and API - $api",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total{endpoint=\"$api\"}[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Flask Total HTTP Calls by Status Code and API - $api",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total{endpoint=\"$api\"}[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Flask Total HTTP Calls by Status Code and API - $api",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total{endpoint=\"$api\"}[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Flask Total HTTP Calls by Status Code and API - $api",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total{endpoint=\"$api\"}[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Flask Total HTTP Calls by Status Code and API - $api",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total{endpoint=\"$api\"}[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Flask Total HTTP Calls by Status Code and API - $api",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total{endpoint=\"$api\"}[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Flask Total HTTP Calls by Status Code and API - $api",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(app_flask_http_request_total{endpoint=\"$api\"}[$delta])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flask Average Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_flask_http_request_duration_seconds_sum[$delta])) /\nsum(rate(app_flask_http_request_duration_seconds_count[$delta]))",
       "legendFormat": "average"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Time by API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flask Average Response Time by API",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_flask_http_request_duration_seconds_sum[$delta])) by (endpoint) /\nsum(rate(app_flask_http_request_duration_seconds_count[$delta])) by (endpoint)",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  }
 ]
}