{
 "title": "Repository",
 "description": "Visualise the performances of the repository.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "delta",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "query",
    "query": "app_repository_query_duration_seconds_count"
   }
  ]
 },
 "panels": [
  { "title": "Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repository Average Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum[$delta])) /\nsum(rate(app_repository_query_duration_seconds_count[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Average by Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repository Average Response Time by Query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum[$delta])) by (query) /\nsum(rate(app_repository_query_duration_seconds_count[$delta])) by (query)",
       "legendFormat": "{{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Average by Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repository Average Response Time by Instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Average by Instance and Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repository Average Response Time by Instance and Query - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "repeat": "query",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Repository Average Response Time by Instance and Query - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Repository Average Response Time by Instance and Query - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Repository Average Response Time by Instance and Query - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Repository Average Response Time by Instance and Query - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Repository Average Response Time by Instance and Query - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Repository Average Response Time by Instance and Query - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Repository Average Response Time by Instance and Query - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) by (instance) /\nsum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repository Response Time Quantiles ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    }
   ]
  },
  {
   "title": "Quantiles by Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repository Response Time Quantiles - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "repeat": "query",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Repository Response Time Quantiles - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Repository Response Time Quantiles - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Repository Response Time Quantiles - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Repository Response Time Quantiles - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Repository Response Time Quantiles - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Repository Response Time Quantiles - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Repository Response Time Quantiles - $query",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "25th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=~\"$query\"}[$delta])) by (le))",
       "legendFormat": "99th"
      }
     ]
    }
   ]
  }
 ]
}